dist: trusty
sudo: required
language: python
python:
  - "3.6"
before_install:
  - sudo chmod +x tests/services_setup.sh
  - sudo tests/services_setup.sh
install:
  - pip install -r requirements.txt
  - pip install -e .
script:
- python -m pytest -v