# Configuration file for Honey Hornet.

# Defines the type of scan to run.
# Uncomment one option only.
scanType:
  - 1  # Port Scan
  # - 2  # Check Credentials

# Ports to scan on each target.
ports:
  - 21
  - 22
  - 23
  - 2332
  - 9191
  - 9443

# Users to test when running in Check Credentials mode.
users:
  - admin
  - root
  - user

# Passwords to test when running in Check Credentials mode.
passwords:
  - admin
  - camera
  - 12345

# Path to list of targets for scanning.
targets:
  # - ~/path/to/target_list.txt
  - targets.txt