# Configuration file for Honey Hornet.

# Defines the type of scan to run.
# Uncomment one option only.
scanType:
  #- 1  # Port Scan
  - 2  # Check Credentials

# Uncomment to do banner grabs on HTTP ports.
bannerGrab: True

# Ports to scan on each target.
ports:
    - 21
    - 22
    - 23
    - 2332
    - 9191
    - 9443

# Users to test when running in Check Credentials mode.
users:
    #- admin
    #- root
    - user
    #- viewer

# Passwords to test when running in Check Credentials mode.
passwords:
  #- admin
  #- camera
  - 12345

# Path to list of targets for scanning.
targets:
  # Something about the path doesn't work with NMAP:
  # - ~/path/to/target_list.txt
  # As long as the file is in the same folder, works fine.
  #- lab_camera.txt
  - targets.txt
